# Generated by Django 4.0.5 on 2022-07-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_inscription',
            old_name='telephone',
            new_name='phone',
        ),
    ]
