# Generated by Django 4.0.5 on 2022-07-04 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pre_inscription',
            name='telephone',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
