# Generated by Django 4.0.5 on 2022-07-04 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_inscription',
            name='telephone',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
